spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: ea7ef465-ecf6-4ffe-bad6-996262a632c3
  expiration: 99999